# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/magen/Documents/Programs/gameboy/gameboy.srcs/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0.xci
# IP: The module: 'display_driver_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/magen/Documents/Programs/gameboy/gameboy.gen/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_driver_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/magen/Documents/Programs/gameboy/gameboy.gen/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_driver_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/magen/Documents/Programs/gameboy/gameboy.gen/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_driver_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/magen/Documents/Programs/gameboy/gameboy.srcs/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0.xci
# IP: The module: 'display_driver_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/magen/Documents/Programs/gameboy/gameboy.gen/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_driver_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/magen/Documents/Programs/gameboy/gameboy.gen/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_driver_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/magen/Documents/Programs/gameboy/gameboy.gen/sources_1/bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_driver_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
