# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/display_driver/display_driver.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_driver || ORIG_REF_NAME==display_driver} -quiet] -quiet

# IP: bd/display_driver/ip/display_driver_vga_verify_0_0/display_driver_vga_verify_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_driver_vga_verify_0_0 || ORIG_REF_NAME==display_driver_vga_verify_0_0} -quiet] -quiet

# IP: bd/display_driver/ip/display_driver_vga_driver_svga_0_0/display_driver_vga_driver_svga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_driver_vga_driver_svga_0_0 || ORIG_REF_NAME==display_driver_vga_driver_svga_0_0} -quiet] -quiet

# IP: bd/display_driver/ip/display_driver_clk_wiz_0_0/display_driver_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_driver_clk_wiz_0_0 || ORIG_REF_NAME==display_driver_clk_wiz_0_0} -quiet] -quiet

# IP: bd/display_driver/ip/display_driver_proc_sys_reset_0_0/display_driver_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_driver_proc_sys_reset_0_0 || ORIG_REF_NAME==display_driver_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/display_driver/ip/display_driver_lcd_to_vga_0_0/display_driver_lcd_to_vga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_driver_lcd_to_vga_0_0 || ORIG_REF_NAME==display_driver_lcd_to_vga_0_0} -quiet] -quiet

# XDC: c:/Users/magen/Documents/Programs/gameboy/gameboy.gen/sources_1/bd/display_driver/display_driver_ooc.xdc
